### ISSUE TITLE
Draft structure and section order

### ISSUE THREAD

**Issue by tlodderstedt** [vcstuff/draft-looker-oauth-jwt-cwt-status-list#19]
I did a first review of this draft. As a newbie to the topic, I found the following issues:

- I miss a description of the fundamental concept, i.e. the status list itself is a JWT (issued by the same issuer issuing the JWTs), the status list JWT is obtained from a URL hosted by that issuer or another party, the link between the JWT and its status list is provided through data in the JWT. I suggest to add this in the Introduction (or an Overview) section. 
- When reading Section 3.1. for the first time I was confused whether it describes the status list JWT or the JWT referring to the status list. I think it is the latter and it should be clear to the reader on first sight. 
- I  think the order of definition should be changed. Right now, I'm supposed to understand how a status list JWT is used in a JWT without even knowing what that status list JWT is. I suggest to change order: 1) Overview of the concepts, 2) specify status list JWT (structure and where/how to obtain), 3) embedding in a JWT (syntax, processing rules, ...).

**Comment by paulbastian** [comment]
Agree on 1+2. As mentioned in #13 we need a better word describing the "Token" that is being described by the status List. I will make a PR using "Subject Token" as this comprises both JSON and CBOR formats.
Agree on 3 as well.

**Comment by paulbastian** [comment]
For reordering it would make sense to get forward with the existing PRs first and do it afterwards..

**Comment by paulbastian** [comment]
Addressing some of these issues in #20

**Comment by paulbastian** [comment]
What's left to do: reorder Status List Token first and Referenced Token afterwards
