### ISSUE TITLE
Add a privacy consideration around suggested list sizes for heard privacy

### ISSUE THREAD

**Issue by tplooker** [vcstuff/draft-looker-oauth-jwt-cwt-status-list#4]
As described in the title the size of the list (number of token statuses represented by the list) will have a significant impact on privacy related applications.

**Comment by paulbastian** [comment]
Should we define a minimum size or give this as a recommendation in privacy recommendation?

**Comment by paulbastian** [comment]
use SHOULD for minimum size 16K
