### ISSUE TITLE
Encode StatusList as JSON Serialisation instead of Compact Serialisation

### ISSUE THREAD

**Issue by paulbastian** [vcstuff/draft-looker-oauth-jwt-cwt-status-list#42]
binary status list data is base64url-encoded for JSON.
JWT then base64url-encodes this data again as part of encoding the body/payload.
Encoding with JWS Compact-Serialisation avoids this and only base64url-encodes the binary status list data once

**Comment by paulbastian** [comment]
transmitting the statusListToken over HTTP with gzip wins much of this overhead back, so the difference isn't as huge

**Comment by bc-pi** [comment]
The JWS JSON Serializations also base64url encodes the payload https://www.rfc-editor.org/rfc/rfc7515#section-3.2 so isn't by itself a way to avoid double base64url encoding.

**Comment by paulbastian** [comment]
@bc-pi thanks for pointing this out, I got this wrong!
